=== Ricardo-Reis-projects/bryanCafe/branches.dtd
<!ELEMENT branches (item+)>
<!ELEMENT item (image, address, contact, hours)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT hours (#PCDATA)>

=== Ricardo-Reis-projects/bryanCafe/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
  <item>
    <!--<url>https://www.google.com/maps/place/76+Devonshire+St,+Surry+Hills+NSW+2010/@-33.885934,151.2051383,17z/data=!3m1!4b1!4m6!3m5!1s0x6b12ae21aea44cd5:0xcf2d54666d7cca73!8m2!3d-33.8859385!4d151.2077186!16s%2Fg%2F11c26pzd8y?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D</url>-->
    <image>images/address1.png</image>
    <address>76 Devonshire St, Surry Hills NSW</address>
    <contact>02 9211 1234</contact>
    <hours>Mon - Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00</hours>
  </item>
  <item>
    <!--<url>https://www.google.com/maps/place/451+Pitt+St,+Sydney+NSW+2000/@-33.8796134,151.2042391,17z/data=!3m1!4b1!4m6!3m5!1s0x6b12ae23192f282b:0x506728c0b18a4f49!8m2!3d-33.8796179!4d151.2068194!16s%2Fg%2F11c5f9whm6?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D</url>-->
    <image>images/address2.png</image>
    <address>451 Pitt St, Haymarket Sydney, NSW</address>
    <contact>02 9262 5678</contact>
    <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
  </item>  
  <item>
  <!-- <url>https://www.google.com/maps/place/31+Alfred+St,+Sydney+NSW+2000/@-33.8621849,151.2083256,17z/data=!3m1!4b1!4m6!3m5!1s0x6b12ae69daa2f96f:0x735f85193da40a66!8m2!3d-33.8621894!4d151.2109059!16s%2Fg%2F12xptsbqw?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D</url>-->
    <image>images/address3.png</image>
    <address>31 Alfred Street, Circular Quay, NSW</address>
    <contact>02 8971 9101</contact>
    <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
  </item>
</branches>
