=== Ricardo-Reis-projects/bryanCafe/menuBeverages.dtd
<!ELEMENT menuBeverages (item+)>
<!ELEMENT item (size, price, description)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== Ricardo-Reis-projects/bryanCafe/menuBeverages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menuBeverages SYSTEM "menuBeverages.dtd">
<menuBeverages>
  <item>
    <size>Small</size>
    <price>3.50</price>
    <description>For coffee, please inform the staff of the coffee type.</description>
  </item>
  <item>
    <size>Regular</size>
    <price>4.00</price>
    <description>For coffee, please inform the staff of the coffee type.</description>
  </item>
  <item>
    <size>Large</size>
    <price>4.50</price>
    <description>For coffee, please inform the staff of the coffee type.</description>
  </item>
</menuBeverages>
