=== Ricardo-Reis-projects/bryanCafe/menu.dtd
<!ELEMENT menu (menuMeal, menuBeverages, menuOthers)>

<!-- Shared elements -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT size (#PCDATA)>

<!-- Menu meals -->
<!ELEMENT menuMeal (meal+)>
<!ELEMENT meal (name, price, image, description)>

<!-- Menu beverages -->
<!ELEMENT menuBeverages (beverages+)>
<!ELEMENT beverages (size, price, description)>

<!-- Menu others -->
<!ELEMENT menuOthers (others+)>
<!ELEMENT others (name, price)>

=== Ricardo-Reis-projects/bryanCafe/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">


<menu>
<!--menu meal-->
  <menuMeal>
    <meal>
      <name>Beetroot and feta salad</name>
      <price>15.00</price>
      <image>Images/beetroot salad2.jpg</image>
      <description>Suitable for vegetarians, made with fresh beetroot</description>
    </meal>
    <meal>
      <name>Sourdough Rye Sandwich</name>
      <price>18.00</price>
      <image>Images/sourdough rye sandwich.jfif</image>
      <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>    
    </meal>
    <meal>
      <name>Spinach Pie and Salad</name>
      <price>20.00</price>
      <image>Images/spinach pie and saldad.jpg</image>
      <description>Tasty pie with salad made with organic spinach</description>    
    </meal>
      <meal>
      <name>Feta pancakes with salad</name>
      <price>19.50</price>
      <image>Images/feta pancakes.jpg</image>
      <description>Tasty this delicious pancake filled with feta and salad</description>    
    </meal>
  </menuMeal>

  <!--menu Beverages-->
  <menuBeverages>
    <beverages>
      <size>Small</size>
      <price>3.50</price>
      <description>For coffee, please inform the staff of the coffee type.</description>
    </beverages>
    <beverages>
      <size>Regular</size>
      <price>4.00</price>
      <description>For coffee, please inform the staff of the coffee type.</description>
    </beverages>
    <beverages>
      <size>Large</size>
      <price>4.50</price>
      <description>For coffee, please inform the staff of the coffee type.</description>
    </beverages>
  </menuBeverages>

  <!--menu others-->
  <menuOthers>
    <others>
      <name>Soda</name>
      <price>3.00</price>
    </others>
    <others>
      <name>Fresh juice</name>
      <price>6.00</price>
    </others>
    <others>
      <name>Bottled water</name>
      <price>2.00</price>
    </others>
  </menuOthers>
</menu>
